### PR TITLE
Moving the settings page as a popup

### PR DESCRIPTION
**Pull request by juleshwar**
1. Made settings more reachable by moving it as a popup
2. Style changes
3. Added a changelog file
4. Bumping version to 4.0

### CODE REVIEW

**Comment by flawyte** [comment]
Hey @juleshwar! Thanks for the PR and sorry about the response delay.
Is there a way to increase the dialog's height? Cause it's a bit too small and not very handy right now.
Otherwise very good job, I love the fact that you "pinned" the button at the bottom and added shadows at the bottom / top when the content is scrolled.

**Comment by juleshwar** [comment]
Hey @flawyte, I'm glad you like the changes. 😄 
I have increased the height to 350px now.

**Comment by flawyte** [comment]
Thanks! Merged.
I've also added the `hacktoberfest-accepted` label, hope it's not too late. Sorry again about the delay, busy month.
Cheers.

**Comment by juleshwar** [comment]
Thank you
No problem, it wasn't late!

**Pull request merged**
